# Keynotes {-}



```{block, type='protip'}

#### Join us at the #OTESSA23 Morning Radio Show Monday, Tuesday, Wednesday, May 29, 30, and 31 from 6:30 – 7:30 am (Eastern) at https://voiced.ca
```

## Glenda Cox & Bianca Masuku {-}

*University of Cape Town*

***Saturday, May 27, 11:00 AM***



Dr Glenda Cox is a senior lecturer in the [Centre for Innovation in Learning and Teaching (CILT)](http://www.cilt.uct.ac.za) at the University of Cape Town and her portfolio includes postgraduate teaching, Curriculum change projects, Open Education, and Staff development. She holds the UNESCO chair in Open Education and Social Justice (2021-2024). She is on the editorial board of the International Journal of Students as Partners (joined in 2022). She is passionate about the role of Open Education in the changing world of Higher Education. Dr Glenda Cox is currently the Principal Investigator in the Digital Open Textbooks for Development (DOT4D) initiative. Her current research includes analysing the role of open textbooks for social justice.

Bianca is a Junior Research Fellow in the Digital Open Textbooks for Development (DOT4D) project and drives the research arm of the initiative. She is currently a PhD candidate in Anthropology at UCT. She holds a Bachelor of Arts degree in Anthropology and Psychology and a Master’s in Social Anthropology from the University of Witwatersrand. Her work has revolved around gender, sexuality, youth and health, with a great interest in how young people experience, interrogate and contribute to the worlds around them. Her doctoral work explores understandings of TB in the township of Khayelitsha through a youth-based community engagement project. Her research background and varied research experiences fuel her current interests in open education, open educational resources, open textbooks and social justice with a keen interest in the inclusion and recognition of student voices.

```{block, type='keynote'}

### Enabling ‘Students as Partners’: Open Textbooks, Power Shifts and Curriculum Transformation {-}

Work done with open textbook creators at UCT has enabled the DOT4D initiative to articulate models of open textbook production that are being employed by academics at UCT who are using their open textbooks to address social (in)justice in the classroom. Building on this background work, we explore the values and attitudes of the academics who undertake open textbook production with student co- creators. Student inclusion is lauded in research as essential for student belonging, but little work has been done to look for the challenges involved when traditional power dynamics are disrupted. In this research, we describe a potential nexus of three complementary components: open textbooks, social justice, and students as partners. We investigate the affordances of the open textbook to facilitate change in the power dynamics of content production as well as in classroom practice.


```

## Sarah Elaine Eaton {-}

*University of Calgary*

***Monday, May 29, 11:00 AM***



Sarah Elaine Eaton, PhD, is an associate professor at the Werklund School of Education, University of Calgary, Canada and an Honorary Associate Professor, Deakin University, Australia. She has received research awards of excellence for her scholarship on academic integrity from the Canadian Society for the Study of Higher Education (CSSHE) (2020) and the European Network for Academic Integrity (ENAI) (2022). Dr. Eaton has written and presented extensively on academic integrity and ethics in higher education and is regularly invited as a media guest to talk about academic misconduct. Dr. Eaton is the editor-in-chief of the International Journal for Educational Integrity.

Her books include Plagiarism in Higher Education: Tackling Tough Topics in Academic Integrity, Academic Integrity in Canada: An Enduring and Essential Challenge (Eaton & Christensen Hughes, eds.), Contract Cheating in Higher Education: Global Perspectives on Theory, Practice, and Policy (Eaton, Curtis, Stoesz, Clare, Rundle, & Seeland, eds.), and Ethics and Integrity in Teacher Education (Eaton & Khan, eds.) and Fake Degrees and Fraudulent Credentials in Higher Education (Eaton, Carmichael, & Pethrick, eds.). She is also the editor-in-chief of the Handbook of Academic Integrity (2nd ed., Springer), which is currently under development.

[Faculty Profile](https://profiles.ucalgary.ca/sarah-elaine-eaton)

[Personal Blog](https://drsaraheaton.wordpress.com/)

[Twitter](https://twitter.com/DrSarahEaton)

[LinkedIn](https://ca.linkedin.com/in/drsaraheaton)

```{block, type='keynote'}

### Academic Integrity in the Age of Artificial Intelligence {-}

How worried do we need to be that students are going to cheat more because of artificial intelligence? Does writing generated by an artificial intelligence (AI) writing app constitute plagiarism? How can artificial intelligence be used ethically for teaching, learning, and assessment? Will a robot take my job?
These questions have dominated teaching and learning circles and social media since late 2022 when ChatGPT emerged. In this Keynote, Sarah provides insights into how AI tools are impacting higher education. She will share insights from recent research project at the University of Calgary that explores the question: What are the ethical implications of artificial intelligence technologies for teaching, learning, and assessment?


```

## Nick Bertrand {-}


*University of Calgary*

***Wednesday, May 31, 11:00 AM***



Nick is a proud Kanyen’keha:ka and member of the Mohawks of the Bay of Quinte. He is a father, partner, uncle, and educator. Sharing truth alongside messages of hope and resiliency through the vehicle of education is what interests and drives Nick.

Nick has worked in education for over 17 years in many roles including: a high school OCT certified teacher, a school board Indigenous Education Lead, and more recently as an Education Officer in the Ministry of Education. In September 2015, Nick was seconded to the Ministry of Education where he had the opportunity to work collaboratively on the development of Ontario’s curriculum strategy for the Calls to Action of the Truth and Reconciliation Commission. Nick currently works in the Indigenous Education Office within the Ministry of Education and also works independently to support the recruitment, hiring, and retainment of Indigenous Peoples in the private sector workforce.

Grounded by the incredible support and generosity of Elders, Knowledge Keepers, community, family, and friends has allowed Nick to share space in a variety of educational settings. To move along a reconciliatory path, Nick has always believed that the foundation of this journey is rooted in strong relationships built on respect, understanding, and reciprocity.
 
```{block, type='keynote'}

### Progressing truth, confronting complacency, and unleashing the possibility of healing through education. {-}

Education as a tool for both healing and reconciliation has been an evolving movement over the years, and in particular since the release the of the Truth and Reconciliation Commission 94 Calls to Action.  Eight years later in a post TRC society, what truths remain untold?  What lessons have we learned in trying to mobilize meaningful change?  How can we as educators, uphold our responsibilities in the work of rebuilding the broken relationship that has brought us to this space? As the reconciliatory bridge continues to be constructed, education systems will continue to play a keystone role in the process of building awareness, understanding, and creating action.


```

## Paul Prinsloo {-}


***Friday, June 2, 11:00 AM***



Paul Prinsloo is a Research Professor in Open and Distance Learning (ODL) in the Department of Business Management, College of Economic and Management Sciences, University of South Africa (Unisa). He is a Visiting Professor at the Carl von Ossietzky University of Oldenburg, Germany as well as at the National Open University of Nigeria (NOUN), a Research Associate for Contact North/Contact Nord (Canada), a Fellow of the European Distance and E-Learning Network (EDEN), member of the Executive Committee for the Society of Learning Analytics Research (SoLAR) and serves on several editorial boards. His research focuses on student success in distributed education contexts, the ethical collection, analysis and use of student data in learning analytics, and digital identities. He was born curious and in trouble and nothing has changed since then.

[He blogs](https://opendistanceteachingandlearning.wordpress.com/) and can be found on [Twitter](https://twitter.com/14prinsp) and [Mastodon.social](https://mastodon.social/@14prinsp).

```{block, type='keynote'}

### The (un)bearable lightness of student data privacy: reckonings and re-imaginings {-}

Education has always collected and used student learning data in combination with a range of other data e.g., demographic, financial and prior learning data for a variety of purposes such as to assess and monitor students’ progress, identify students who may need additional support. There has always been concerns about possible bias, stereotyping and impact of categorization of students. Students’ (data)(learning) privacy were somewhere to be found among files being carried from one office to the other, files that got misplaced, unlocked storages and, possibly, a laissez-faire approach to protecting student data privacy because what happened in the classroom and school, stayed in the classroom (mostly). Even if this portrayal of student data privacy may sound idealistic and rather, simplistic, we must reckon how the increasing digitalization and datafication of teaching and learning changes not only the scope of student (data) privacy, but also attempts to protect their (and our) data. In this presentation I hope to provoke thinking about the (un)bearable lightness of student data privacy and consider what it means for students, faculty, institutional data governance amid the intensification and expansion of the data gaze. 


```

## Congress Events {-}

```{block, type='vendor'}


###  [Click here to access a schedule of all open Congress events.](https://www.federationhss.ca/en/congress/congress-2023/events-calendar){target="_blank"}

```
