# Monday, May 29 | In Person at York University

```{block, type='protip'}

#### Join us at the #OTESSA23 Morning Radio Show Monday, Tuesday, Wednesday, May 29, 30, and 31 from 7:30 – 8:30 am (Eastern) at https://voiced.ca
```

### Session Types {-}

```{block, type='protip'}


#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='keynote'}

#### Keynote

```

```{block, type='speaker'}

#### Invited Speaker

```

```{block, type='session'}

#### Regular Session

```

```{block, type='social'}

#### Social Session

```

```{block, type='vendor'}


#### Vendor

```

```{block, type='workshop'}


#### Workshop

```

---

## Continental Breakfast Provided | 8:00-9:00 {-}

## Welcome Desk Open | 8:00 - 11:30 {-}

## Conference Welcome, Announcements & Land Acknowledgement | 9:00-9:15 {-}

<mark>**Life Sciences Building LSB 103 @ York**

**See the Virtual Congress Platform for Zoom Links**

## Break | 9:15-9:30 {-}

## Concurrent Session 5 | 9:30-10:30 {-}

### Concurrent Session 5.1 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 105**</mark>

```{block, type='session'}

#### 9:30 - 10:30 | **Cultivating Essential Leadership Skills for Digital Transformation in Ontario Postsecondary Education** |  Practice {-}

***Alissa Bigelow & Monica Shah*** | *eCampusOntario*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Digital Transformation (Dx) involves more than implementing new technologies; it requires a shift in organizational culture and the acceptance of digital tools as an integral component of organizational activity. A foundational component to digital transformation in Ontario’s postsecondary sector will be ensuring leaders understand how their influence impacts institutional culture and how that culture either promotes or inhibits innovation. At their core, a Dx leader is responsible for inspiring action within their organization, department, team, classroom, and learners in new and innovative ways.

Researchers conducted an environmental scan and qualitative survey for postsecondary leaders and educators to identity gaps in supports of leadership development for Dx. The survey revealed that agility, critical thinking, foresight, data security, analysis, governance, and technology selection and evaluation are key competencies where limited sector level support is available for leaders facing an increasingly digital future. The research team refined these competencies into a five-module professional development program intended to be delivered in online self-paced and interactive facilitated formats.

This presentation will discuss the research efforts, competency framework and curriculum development to date. Anyone, at any level of an organization, has the capacity to be a leader, and effective leaders will recognize that capacity in others. The audience will engage in a key activity to take the first step toward becoming a transformative leader for Dx within their institution.

</p>
</details>
```

### Concurrent Session 5.2 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 103**</mark>

```{block, type='session'}

#### 9:30 - 10:30 | **Ascending the Mountain: Examining National Open Educational Resource (OER)** |  Practice {-}

***Michael McNally*** | *University of Alberta*

***Catherine Lachaîne*** | *University of Ottawa*

***Ann Ludbrook*** | *Toronto Metropolitan University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
This session examines ongoing work by a multi-stakeholder group to develop sustained federal advocacy initiatives for open educational resources (OER) in Canada, including a National Advocacy Framework. It begins by reviewing national OER advocacy work including the 2018 pre-budget consultation, and the development of regular meetings around national OER advocacy. One outcome of the meetings was the creation of a working group to develop a National Advocacy Framework for Open Educational Resources in Canada (CARL, 2023). The session reviews the Framework’s arguments for federal involvement in OER. It subsequently discusses a series of targeted national working summits of specific issues focused on OER involvement. This includes discussing the November 2022 summit on policy and infrastructure, the planned May 2023 summit on Francophone OER, and the third summit on Indigenous OER. Engagement strategies and the next steps in advocacy work, including the development of prioritized and targeted advocacy statements are discussed. This portion leads the discussion section (15-20 minutes) where attendees will be able to ask questions and discuss how future advocacy work should be shaped. The focus on discussion is underpinned by a commitment to developing a sustained initiative of a diverse array of OER stakeholders on national advocacy.

</p>
</details>
```

### Concurrent Session 5.3 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 101**</mark>

```{block, type='session'}

#### 9:30 - 10:00 | **Mythical Beast, Panacea or Breaking News: Open Education Policy in Higher Education Institutions** |  Research {-}

***Leo Havemann*** | *University College London / Open University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Much discussion of open education policy has occurred at the supranational level (e.g., UNESCO, 2019) and in some cases, nations and subnational governments have taken up the challenge of incorporating open resources and practices into policymaking. What is less clear, and less straightforward to investigate, is the extent to which individual higher education institutions are developing policy to support aspects of openness.
This session reports on doctoral research work-in-progress investigating the institutional open education policy space. A survey instrument was developed and distributed in order to seek the views of HE staff members internationally. In order to frame the research questions and instruments, inclusive understandings of the concepts ‘open education’ and ‘institutional policy’ have ben adopted. Open education can be described as a wide umbrella term, which can potentially refer to many practices across formal, informal and non-formal education (Author, 2016; Weller et al., 2019). ‘Institutional policy’ is considered to include documented policies, strategies, regulations or guidelines, but also for example, provision of infrastructure, usual courses of action, regular aspects of a person’s work, or funded or supported areas of activity (Author, 2020).
Participants in the survey were therefore asked for information and opinions about the intentions and effects of local institutional policies on areas of practice including:
- use, creation, sharing and adaptation of open educational resources (OER).  
- offering of free and lower-cost online courses.  
- opening up of aspects of learning, teaching and assessment to external participants, partners and audiences.  
- participating in open professional development communities of practice.  
The presentation will give an overview of the findings from the survey and consider implications for OE advocates seeking to enhance support for OEP within institutions through policy.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **myWATERSHED: A Serious Game for Fostering Sustainability Champions of the Future** |  Research {-}

***Isabelle Barrette-Ng*** | *University of Windsor*

***Adam Clare*** | *Sheridan College*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Restoration ecology courses stress that students learn the knowledge and leadership skills necessary to successfully restore degraded regions. Yet, traditional classrooms offer limited opportunities to plan and implement restoration due to barriers of ecological, spatial, and temporal scale. To train and empower youth to take on the challenge of ecological restoration, we created the myWATERSHED sandbox game. myWATERSHED utilizes a digital twin of the Humber river watershed to engage learners in restoration using an endangered species, the redside dace. The game creates a realistic simulation where the interactions explore ecological principles and critical challenges, including the concept of spatial, temporal and ecological scale in restoration. myWATERSHED allows students the freedom to explore and manipulate a realistic environment where they can assess restoration strategies, implement efforts under resource constraints, and solicit feedback. Through an autoethnographic process, we will share our experience in building and coordinating the efforts of a multidisciplinary team to create a serious game. We invite participants to share ideas to improve the design of the software and the approach used to manage an interdisciplinary team for educational software development. We hope to hear how participants could adapt or incorporate the game or our approach in their own contexts.

</p>
</details>
```

### Concurrent Session 5.4 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 107**</mark>

```{block, type='session'}

#### 9:30 - 10:00 | **Early Findings on an Experiment in Distance Education with High School Students** |  Research {-}

***Alexandre Lanoix, Normand Roy, Marc-André Éthier*** | *Université de Montréal*

***Serge Gérin-Lajoie*** | *Université TÉLUQ*

***Bruno Poellhuber*** | *Université de Montréal*


<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Recent years have seen an important increase in distance education at K-12 levels. Our research is based on 22 interviews conducted with high school students enrolled in a distance education history course. Results show that some of them greatly missed social interactions and that their motivation and grades suffered from taking courses in that format. On the other hand, some students thrived in that setting and welcomed the increased autonomy and flexibility it provided. In a context where distance education is considered a viable option in an increasing number of cases for high school students, our results indicate that it is not suitable for all students and that some aspects of student support are central to fostering students’ engagement and achievement.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **Over the Threshold: Graduate Student Needs in Academic Publishing** |  Research {-}

***Christie Hurrell, Susan Beatty*** | *University of Calgary*

***Dana Cramer*** | *Toronto Metropolitan University*

***Jennifer Lee, James Murphy & Caitlin McClurg*** | *University of Calgary*
<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Graduate students are under increasing pressure to participate in academic publishing during their studies, yet comprehensive mentorship and education on this topic may not be available to all students. This study conducted focus groups with graduate students and faculty advisors, to better understand what is challenging to learn and teach on the topic of academic publishing. The purpose of this research was to improve educational supports for graduate students learning how to publish their scholarly research. Academic publishing is referred to as a ‘threshold concept’ in the literature, as students develop a transformational understanding of the academic profession once they gain this knowledge (Townsend et al., 2011). The research team developed a blended learning approach to teaching and learning gaps identified by focus group participants. Our approach uses the lens of “compassionate pedagogy” and comprises both an on-demand, multimedia Open Educational Resource and in person approaches to build community and address the mental wellness aspects of the complex topic of early career academic publishing.

</p>
</details>
```

## Break | 10:30-11:00 {-}

## Keynote | 11:00-12:00 {-}

<mark>**Lassonde Building LAS C**</mark>

**See the Virtual Congress Platform for Zoom Links**

```{block, type='keynote'}


#### Academic Integrity in the Age of Artificial Intelligence {-}

[***Sarah Elaine Eaton*** | *University of Calgary*](https://otessa.github.io/2023/keynotes.html#sarah-elaine-eaton)

<details>
<summary><b>Abstract</b></summary>
<p>
How worried do we need to be that students are going to cheat more because of artificial intelligence? Does writing generated by an artificial intelligence (AI) writing app constitute plagiarism? How can artificial intelligence be used ethically for teaching, learning, and assessment? Will a robot take my job?

These questions have dominated teaching and learning circles and social media since late 2022 when ChatGPT emerged. In this Keynote, Sarah provides insights into how AI tools are impacting higher education. She will share insights from recent research project at the University of Calgary that explores the question: What are the ethical implications of artificial intelligence technologies for teaching, learning, and assessment?
</p>
</details>


##### [Session Link](){target="_blank"} {-}

```

## Break | 12:00-1:30 {-}

## Parallel Session 6 |  Invited Speakers | 1:30-2:15  {-}

45 Minutes

### Parallel Session 6.1 {-}

<mark>**Life Sciences Building LSB 103 @ York**

**See the Virtual Congress Platform for Zoom Links**

```{block, type='speaker'}

####  **Jennifer Wemigwans** | *OISE University of Toronto* {-}

*Digital Bundles: A Reckoning and a Re-imagining *

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Digital Bundles create cultural space for Indigenous Knowledge through the use of new technologies. The concept for Digital Bundles comes from a tradition that respects diverse Elders and Knowledge Keepers as the custodians of community Knowledge Bundles. Sharing Digital Bundles online represent new spaces for Indigenous Knowledge in the form of Open Education. Digital Bundles are both a Reckoning and amRe-imagining of online space. For non-indigenous audiences, Digital Bundles challenge them to step outside of their codified systems and learn a new way of being and perceiving the world. For Indigenous audiences, Digital Bundles are a new way to share the brilliance of diverse Indigenous Knowledges with new generations.

</p>
</details>
```

### Parallel Session 6.2 {-}

<mark>**Life Sciences Building LSB 105**</mark>

**See the Virtual Congress Platform for Zoom Links**

```{block, type='speaker'}

#### Isabel Pedersen | Ontario Tech University

*Shock and Awe: Generative AI Composition, Cultural Adaptation, and Postsecondary Education*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The launch of OpenAI’s ChatGPT was a dramatic event making generative artificial intelligence a mainstream phenomenon. Data journalist, Katharina Buchholz explains that “ChatGPT gained one million users just five days after launching in November” of 2022 (Statista, 2023). Generative AI can produce stylistically correct sentences, paragraphs, and documents across a multitude of genres. It can produce professional-grade visual images and video. While heavily debated, one could argue that generative AI ‘creates’. Consequently, generative AI can help students create art, write, or collaborate with other students. However, generative AI can complete all of these tasks for students without requiring much human effort, disturbing the general premise of learning to compose. At the same time, its creations are vulnerable to producing false information and discriminatory results due to the training sources. This presentation argues that shock instigated by large tech companies, releasing these products through the rhetoric of hype and fear, is fuelling mass adoption rather than a measured approach. Educators, students, and university administrators are faced with handling the cultural adaptation to AI generators that challenge traditions of human creativity and formal education. Drawing on media studies and rhetoric (Pedersen and Iliadis 2020), digital literacy studies (Duin and Pedersen 2021), and critical AI studies (Bender, Gebru, McMillan-Major, and Shmitchell 2021), this talk points to the process of re-imagining learning expectations in university courses amid the onslaught of generative AI emergence.

</p>
</details>
```

## Break | 2:15-2:30 {-}

## Concurrent Session 7 | 2:30-3:00 {-}

30 Minutes

### Concurrent Session 7.1 |  Wildcard {-}

<mark>**Life Sciences Building LSB 103**</mark>

```{block, type='vendor'}

#### 2:30-3:00 | **The Impact of Social Annotation on Learning** |  Research {-}

**Will be repeated online in Session 18.3 (Friday, June 2)**

***Sean O'Reilly*** | *hypothes.is*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Social Annotation takes the age-old process of marking up texts to the digital learning space. Using social annotation, students and professors can make meaning of text, have conversations around and with the text, and work together to become more proficient readers of academic material. During this session, you will be introduced to social annotation and the various ways it can impact student learning in your courses.

</p>
</details>
```

### Concurrent Session 7.2 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 101**</mark>

```{block, type='session'}

#### 2:30-3:00 | **What Uses of Digital Technology Support and Enhance the Learning and the Engagement of Diverse Learners in High School Classes?** |  Research {-}

***Mourad Majdoub, Fatme Diab & Géraldine Heilporn*** | *Université Laval*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Modern technology plays an important role in helping students from all walks of life to overcome barriers and benefit from teaching and learning. However, due to a lack of knowledge or skills with regards to educational technologies, K-12 teachers struggle to harness the full potential of digitalisation to support student learning and engagement, causing a risk of marginalisation (Chevalère et al., 2021). The gap in using ICTs is known as the digital divide. Research literature has revealed three levels of digital divide: access, usage and outcomes. In response to these research gaps, the aim of this communication is to explore which high school teaching practices cater for learners’ needs and preferences for the sake of an inclusive use of digital technology that enhances their learning and engagement. As part of a research project funded by the SSHRC, we have conducted individual semi-structured interviews with high school teachers and students aiming to obtain in-depth qualitative data mainly through open-ended questions. A thematic analysis has been employed to inductively analyse the interview data and generate possible themes and categories based on the objectives of our study. Preliminary findings will be available in spring 2023, and will be shared at the OTESSA conference.

</p>
</details>
```

### Concurrent Session 7.3 |  Addressing Inequities {-}

<mark>**Life Sciences Building LSB 105**</mark>

```{block, type='session'}

#### 2:30-3:00 | **Personal, Institutional, and Societal Barriers to Educators’ Engagement with Datafication on Campus: A Case Study** |  Research {-}

***Bonnie Stewart, Erica Miklas, Samantha Szcyrek & Thu Le*** | *University of Windsor*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Datafied digital systems have permeated higher education over the past decade. Registration, grading, financial operations, alumni communications, and often teaching take place through digital platforms that extract and collate data, about students as well as faculty and staff. At the level of these data system processes, academics may not have the knowledge or practices to fully grasp the shift in their workplace that datafication represents. However, our research suggests that educators do understand the paradigm shift that datafication represents, and have strong beliefs about how institutions should proceed to protect students and academia itself. Our team conducted an in-depth Comparative Case Study (CCS) investigation of how university educators make sense of the datafied infrastructures in and on which they work. This presentation overviews the knowledge, practices, experiences, and perspectives of educators in various institutional status positions from six different countries, in relation to datafied digital tools. We will focus particularly on the barriers that participants articulated to their own engagement with data, at personal, institutional, and societal levels. We will frame ways barriers are reinforced by institutional approaches to datafication, overview participants’ concerns, and explore how datafication has altered faculty’s power position as knowers within the academy.

</p>
</details>
```

## Break with Coffee and Snack Provided | 3:00-3:30 {-}

## Concurrent Session 8 |  3:30-5:00 {-}

### Concurrent Session 8.1 |  Addressing Inequities {-}

<mark>**Life Sciences Building LSB 105**</mark>

```{block, type='workshop'}

#### 3:30-5:00 | **The Wikidata Lexicographical Data: From Recording of Words to Lexemes and Beyond** |  Workshop {-}

***Sadik Shahadu*** | *MHz Foundation*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Since the start of Wikidata in 2012, the multilingual knowledge base has been mainly focused on concepts: Q-items are related to a thing or an idea, not to the word describing it. Since 2018, Wikidata has also stored a new type of data: words, phrases, and sentences, in many languages, described in many languages. This information is stored in new types of entities called lexemes (L), forms (F), and senses (S).
This workshop session will walk participants through editing the lexicographic data namespace in Dagbani, English, and one additional language with the help of participants. They will also learn more about how Abstract Wikipedia is developed.

</p>
</details>
```

### Concurrent Session 8.2 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 101**</mark>

```{block, type='session'}

#### 3:30-4:30 | **Practitioner Values in the Transition to Open Education Resources: Moving Through Disruption to Improved Practice** |  Practice {-}

***Trista Hill*** | *Athabasca University*

***Gloria Ramirez*** | *Thompson Rivers University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Prior to the global disruption caused by the COVID-19 pandemic, we were engaged in research which closely examined Open Educational Resources (OER) textbook features that respond to the needs of diverse learners, specifically, international students and mature learners. We realized the use of OER reduced educational costs for students and could potentially facilitate students’ learning by allowing for the incorporation of multi-modal (e.g., videos, audios) learning tools as well as other interactive features (e.g., application activities to test learning with immediate feedback). Our guiding research question at the time was: What does an OER for research methods require to address the needs of diverse learners? We had collected survey results, conducted focus groups and were moving towards additional data collection and the development and testing of an OER in research methodologies for students in the Masters of Education program. This promising research was paused in March of 2020 as COVID-19 disrupted our lives and forced us to turn our efforts towards learning how to teach through online alternative modes of instruction. This new reality, opened space for an evolution in our values as educators and our understanding of open pedagogy and OER praxis. After an almost two-year hiatus, inspired by the work of Meger et al (2021), we resumed our collaboration by engaging in structured reflection to examine how we have evolved as educators and researchers engaged with OER development and where we anticipate taking the research from this new place of maturity. Today, we are better positioned to answer that question after being influenced by factors that shifted our perspectives and values.

We will share our initial insights into student perspectives of OERs and follow with a critical examination of existing OERs relevant for research methods in education to identify the extent to which they reflect the values we now adhere to. Our interactive presentation will inspire educators, instructional designers and OER researchers to reflect upon their values and understanding of open education practices. It is through this structured reflection that collectively we can capitalize on opportunities for transformation even through the complexities of a crisis such as the Covid-19 pandemic.

</p>
</details>
```

```{block, type='session'}

#### 4:30-5:00 | **Showcasing a Student-Led Anti-Racism Virtual Simulation Module for Equitable Learning** |  Practice {-}

<mark>**Life Sciences Building LSB 101**</mark>

***Mujeedat Lekuti, HanShu Pu, Rishika Gowda, Zainab Baig, Javeria Baig, Alexandra Lawrynuik*** | *Queen’s University Canada*

***Laura Killam*** | *Cambrian College*

***Marian Luctkar-Flude*** | *Queen's University Canada*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
White-centric perspectives manifest in many North American higher education cultures and systems, which results in inequities disproportionately impacting learners of colour’s well-being. Such racial aggressions produce ‘racial battle fatigue,’ referring to the impact of physiological, physiological, and behavioural stress. Virtual simulation is proposed as an educational strategy to raise awareness of racism in an academic setting and promote allyship for equity-seeking groups. A virtual simulation module was developed to bring awareness to racism. It consists of introductory videos, two simulations, resources, and debriefing prompts and is developed based on lived and observed experiences of a diverse group of learners and educators. The scenes highlight the need to retire the term ‘micro’agression and allow participants to take on the role of a bystander and follow the ARISE model, encompassing five key elements: (1) awareness, (2) responding with empathy, (3) inquiring about facts, (4) using “I” statements, and (5) educating and engaging. With this, we seek to bring awareness of racial inequities in the curriculum by: (1) illustrating how racism affects people in their learning environment, (2) demonstrating how bystanders might apply the ARISE model to help a person experiencing racism in an educational setting, and (3) learning how to be an ally. Addressing covert and overt racism instances may translate to more equitable learning.

</p>
</details>
```

### Concurrent Session 8.3 |  Wildcard {-}

<mark>**Life Sciences Building LSB 103**</mark>

```{block, type='session'}



#### 3:30-4:30 | **Adaptive Learning in Practice** |  Practice {-}

***Don Eldridge*** | *eCampusOntario*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Adaptive learning (AL) leverages the power of technology to continuously modify instructional content based on the behaviours and needs of learners resulting in a personalized learning experience. In 2021, the researchers conducted an environmental scan to discover if and how adaptive learning technologies are being leveraged in Ontario’s higher education sector. While the scan did not identify any large-scale adaptive learning projects, it did find that educators in Ontario see great value in these innovative technologies but that they perceive them as expensive and complex. Based on these findings, in 2022 the researchers conducted a series of webinars for the postsecondary sector with the objective of building a greater awareness of adaptive learning and countering the prevailing narrative of complexity. These webinars featured six Ontario institution and edtech vendor collaborations using different types of adaptive technologies that personalize learning pathways. This practice-based presentation will feature a compilation of best practices derived from these collaborations and provide attendees an opportunity to explore some of the featured technologies.

</p>
</details>
```


```{block, type='session'}

#### 4:30-5:00 | **Conducting Scoping Reviews: Opportunities and Challenges for Examining Social Media Use for Learning** |  Research {-}

***Richard Hayman & Erika E. Smith*** | *Mount Royal University*

<mark>**Life Sciences Building LSB 101**</mark>

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
There is growing recognition among scholarly communities of the value that literature reviews contribute to synthesizing knowledge and understanding important research issues. While different review methodologies (e.g., scoping, systematic, meta-analysis, etc.) use distinct standards and methods, they typically share a common purpose: to position and connect a particular research problem within a greater context, to identify related research, and to provide a direction and rationale for further study in the area (McGregor, 2018). In looking back on, and ahead to, key issues, trends, and gaps in the field of educational technology, conducting reviews and examining the methodological approaches used in reviews are necessary activities.

Speaking to the theme of “Reckonings and (Re)Imagining,” in this session, we will critically discuss why and how such reviews can and should contribute value, now and into the future. Using the case of our current review project on undergraduate use of social media technologies, and with the scholarship of teaching and learning (SoTL) as our primary lens, we will present an example process for establishing a scoping review protocol. By taking stock of the wider opportunities, challenges, and lessons learned for scoping reviews as meta-research contributions to the field, we invite critical discussion amongst SoTL and educational technology scholars considering ways to potentially enhance or extend their own literature review processes.




 
</p>
</details>
```

### Concurrent Session 8.4 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 107**</mark>

```{block, type='session'}

#### 3:30-4:30 | **Intentionality, Community, and Well-being: Re-imagining Blended Course Design** |  Practice {-}

***Brian Lorraine*** | *Simon Fraser University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Engaging in a discussion of key findings, this session aims to contribute to a shared understanding of successes and challenges experienced while fostering a blended learning community of practice. By implementing a Faculty Learning Community (FLC) model, a small team from the Centre for Educational Excellence at Simon Fraser University aimed to support instructors through collaboration on the design and development of blended courses. Facing two significant challenges of pandemic burnout and widely varying proficiency with the use of learning technology, the FLC model aimed to keep well-being at the forefront with a focus on intentionality and community. Early observations reveal mixed results in terms of course design outcomes and instructor perception of their blended learning journey. Through the process, important questions about institutional approaches to blended learning have come into view, and will serve as the basis for discussion both in the session and moving forward.

</p>
</details>
```

```{block, type='session'}

#### 4:30-5:00 | **L’apprentissage en ligne au Québec : résultats de l’enquête annuelle 2022 de l’ACRFL (in French)** |  Practice {-}

***Bruno Poellhuber & Simon Parent*** | *Université de Montréal*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
TBA
</p>
</details>
```

## See Congress Programming for Social Tent & Food Options | 5:00-7:00 {-}

## OTESSA Social |  Life Sciences Building Lobby | 7:00-11:59 {-}