# Tuesday, May 30 | In Person at York University

```{block, type='protip'}

#### Join us at the #OTESSA23 Morning Radio Show Monday, Tuesday, Wednesday, May 29, 30, and 31 from 6:30 – 7:30 am (Eastern) at https://voiced.ca
```

### Session Types {-}

```{block, type='protip'}


#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='keynote'}

#### Keynote

```

```{block, type='speaker'}

#### Invited Speaker

```

```{block, type='session'}

#### Regular Session

```

```{block, type='social'}

#### Social Session

```

```{block, type='vendor'}


#### Vendor

```

```{block, type='workshop'}


#### Workshop

```

---

## Continental Breakfast Provided | 8:00-9:00 {-}

## Welcome Desk Open | 8:00 - 11:30 {-}

## Conference Welcome, Announcements & Land Acknowledgement | 9:00-9:15 {-}

<mark>**Life Sciences Building LSB 103 @ York**</mark>

**<mark>[Session Link](https://uvic.zoom.us/j/89902859924?pwd=VisxNW1GUW5KWnJldW1DRjF2d0Rmdz09)</mark>**

## Break | 9:15-9:30 {-}

## Concurrent Session 9 | 9:30-10:30 {-}

1 hour

### Concurrent Session 9.1 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}

#### 9:30-10:00 | **Developing Open Education Literacies in Teacher Education Programs** |  Research {-}

***Michael Paskevicius*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Researchers have argued that K-12 teachers are well suited to both adopt and develop aspects of open education. DeBarger (2019), suggests that open educational resources (OER), specifically, may be an effective alternative to traditional resources to enhance both student and teacher agency. Marcus-Quinn and Hourigan (2017), acknowledge OER in the development and improvement of teaching effectiveness through more open sharing and development of pedagogy. Similarly, Allen and Katz (2019) posit that teachers are well-positioned to evolve open educational practices and saw that increasing their opportunities to engage openly in a safe environment may impact their self-efficacy and willingness to share openly in the future (Allen & Katz, 2022). Yet, scholars have argued that the research and practice of open education in K-12 is underdeveloped, lacks policy direction, and thus awareness remains low (Blomgren, 2018; Blomgren & MacPherson, 2018).

Teacher education programs have a key role to play in developing open education literacies during teacher training. Taking an expansive view of open education, this may include developing competencies around pedagogical approaches, resource selection, assessment design, and technology use that is driven by openness. There appear to be similar themes in teacher education programs such as accessibility, community engagement, inquiry-driven learning, multimodality, growth mindset, collaboration, mindfulness, and multiculturalism that align well to open educational practices.

This presentation will focus on the ways in which teacher educators might bring aspect of open education into teacher education programs. I will share the results of a literature review on open education in K-12 contexts, a preliminary survey that identifies awareness gaps related to open education, and invite reflections on how teacher educators might introduce open education to emerging teachers in a meaningful way.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **Technological Distance: A New Way of Conceptualizing the “Distance” in Distance Learning** |  Research {-}

***Jon Dron*** | *Athabasca University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
This paper presents the concept of technological distance, which describes a gap between technologies (broadly defined to include methods, tools, principles, and processes) available for a learner to learn, and those needed to complete that learning. This gap is a measure of both the participation and autonomy of learners in the process. Available technologies may include those provided by teachers and institutions as well as from many others, most notably including the learners themselves. The technologies that make up the assembly are only components, however. What matters most is how learners fill the gaps between them to achieve their learning goals. These are fundamentally situated, idiosyncratic, and human. Technological distance provides new insights into other models that use spatial metaphors, such as the presences of communities of inquiry and transactional distance.

</p>
</details>
```

### Concurrent Session 9.2 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 9:30-10:00 | **Belonging, Relatedness, Connectedness, or Social Presence? Overlaps and Differences in Online Learning** |  Research {-}

***Behnoosh Khoramrooz, Mariel Miller & Valerie Irvine*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Feeling connected and supported in online learning-related studies has been mentioned as an essential factor in motivation, engagement and persistence. Following key elements like having an individualized conversation, providing support, promoting cooperation, demonstrating awareness, showing care, acceptance, and help and providing the opportunity to have friendly communication lead us to different constructs in the area, like relatedness, sense of belonging, connectedness, and social presence. The question is, what are the differences between these constructs? And how each of them contributes to the online learning context. This session dedicates to comparing these constructs by referring to their definitions, roots, theories, and contributions to online learning research.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **Hybrid Learning in Ontario During COVID-19 Emergency Closures** |  Research {-}

***Beyhan Farhadi*** | *York University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
This presentation approaches online learning during COVID-19 emergency closures through the lens of critical policy analysis, through which policy is understood as not just responding to but also productive of problems. Drawing from the second phase of a two-year study on the enactment of COVID-19 education policy by secondary teachers, we analyse the context for and expansion of hybrid learning in Ontario. Hybrid learning broadly refers to the simultaneous teaching of students online by a teacher with students in-person. During March and April 2022 we spoke with nine teachers in three school districts to understand variables impacting their enactment of hybrid learning in a rapidly changing context of crisis that our study found impacted student and teacher well being, workload, and educational equity. Findings juxtapose the stated aims of public education and the demands of crisis alongside the realities confronting students and teachers. This reflects equity concerns, including access to the internet and technology, digital literacy, and considerations for privacy and surveillance.

</p>
</details>
```

### Concurrent Session 9.3 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}

#### 9:30-10:00 | **Writing Care-fully about Indigenous Cultural Safety and Cultural Humility: A Reflection by Settlers Engaged in Reconciliation in OER Development** |  Practice {-}

***Deb Nielsen*** | *College of New Caledonia*

***Emily Ballantyne*** |  *Mount Saint Vincent University*
<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
What are ethical ways to engage in reconciliation as settlers who want to incorporate Indigenous contexts and cultural safety into an Open Educational Resource? In this presentation, we discuss the strategies, successes, and challenges of engaging in collaborative open education resource development in a project where the main collaborators were settlers who wanted to engage deeply in reconciliation. This presentation describes our journey and the ways we engaged with a variety of stakeholders to ethically, thoughtfully, and care-fully produce our resource.

A main aspect of our discussion will be around how we engaged in collaboration, community discussion, and sought outside authority with Indigenous experts. We discuss our own experiences with cultural humility and alternative ways of knowing. We are not speaking as experts with deep roots and relationships in the communities we engaged with; instead, we are speaking as newcomers and settlers engaged in this work and struggling with how to do it better. Indeed, this discussion will be about some of the strategies we tried and the lessons we learned and want to take forward to future projects.

</p>
</details>
```

```{block, type='session'}

#### 10:00-10:30 | **Artificial Intelligence Writing in Higher Education: A Teaching and Learning Centre Perspective** |  Practice {-}

***Emily Ballantyne*** | *Mount Saint Vincent University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The launch of ChatGPT has caused seismic shift in the field of higher education. Amidst calls to ban it from schools and decrying the end of entire disciplines (Thomas 2023; Herman 2022; Vincent 2023, Stokel-Walker 2022), there have also been great surges of enthusiasm and optimism as faculty and students alike contend with how this will shape their educational experience going forward. The current crisis caused by artificially intelligence text generators is primarily pedagogical: how does this tool change how we approach learning?
This presentation will explore the emerging issue of artificially intelligent writing from the perspective of a Teaching and Learning Centre. With a mission to support faculty across multiple disciplines engaged in assessment and feedback, it is our job (and our pleasure!) to help source solutions for common teaching problems. In the case of ChatGPT, however, targeted evidence-based strategies have yet to be developed. At the same time, the conversations about the tool are highly charged and fuelled by intensive media coverage of varying quality, all produced extremely quickly and often written to be highly inflammatory and fearmongering. Within our context, this means that in addition to providing accurate and useful information, we also need to work to decode and determine disinformation. It is our role to help apply the existing scholarship of teaching and learning to this new and novel problem. It is also our role to listen and disseminate the lived experience of faculty and students engaged with this work. Further, it is our role to be co-creators of this new knowledge as we work alongside our faculty peers to help, through trial and error, navigate this new educational landscape we find ourselves in.

</p>
</details>
```

## Break | 10:30-11:00 {-}

## UnConference on Digital, Online, and Open Education (On-Site at York) | 11:00-12:00 {-}

**Locations spread across LSB 101, 103, 105, 107. See OTESSA program website for details.**

An unconference is a participant-driven session meant to reduce emphasis on formal speeches and to avoid the hierarchical aspects of a didactic conference session. All Congress attendees are welcome to participate in this face-to-face unconference; however, participants registered with the OTESSA conference will be sent an invitation for topic suggestion and upvoting to select the break-out room topics in advance. At the time of this session, the topic-to-room assignments will be complete and posted on our program website at <https://otessa.org/2023/program/>. You are welcome to move between topic rooms and come and go as you please! We look forward to welcoming targeted discussion on your favourite topics! Please note that this is the in-person unconference. There will also be an online unconference that will take place on Friday, June 2 from 12:30 - 1:15 pm in a Zoom room as part of the OTESSA Conference.


## Lunch Break & Streamed Congress Programming | 12:00-1:30 {-}

## Parallel Session 10 |  Invited Speakers  | 1:30-2:30 {-}

45 Minutes

### Parallel Session 10.1 {-}

<mark>**Life Sciences Building LSB 103**</mark>

**<mark>[Session Link](https://uvic.zoom.us/j/86250728368?pwd=dEFWYXJQcy9uVm91dDArT0RzanVNQT09)</mark>**

```{block, type='speaker'}

#### Bonnie Stewart | University of Windsor 

*Digital Education in an Age of Data: What Do We Do Now?*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Digital Education in an Age of Data: What Do We Do Now?
What does the current digital ecosystem of pervasive digital surveillance, data mining, and encroaching AI mean for the participatory possibilities of open pedagogy and digital learning? What constitutes a critical, ethical response to this increasingly colonizing and extractive ecosystem?

Drawing on two core – and potentially contradictory – patterns of change that intersect in digital learning right now, this talk will focus on the the ethical quandary this intersection creates for open and digital education. On one side are the relational, participatory open digital practices that utilize the infrastructure of the web to engage learners in knowledge abundance. On the other is the datafication of higher education and the resultant enclosure of the platforms on which open practices occur, by data-extractive and even predatory corporate entities. The session will examine how the rise of datafied tools and AI demands a critical and ethical response, but one that our contemporary ‘click yes’ culture makes extremely difficult to mount. It will outline the logics of market capture and hype that currently shape narratives around digital tools, and the barriers this creates for the development of genuine, critical, agential data and AI literacies among faculty and students.

The session is designed to raise questions rather than offer answers, but will highlight two current digital classroom projects that the presenter uses to try to bridge the tensions noted above. These projects aim to foster open practices and data literacies among pre-service teachers, and to encourage them to see their roles as knowledge workers in a new light. The talk will invite participants to consider our mutual – if always differential – responsibility to approach digital and open education with a critical eye to the complex and often potential harmful digital ecosystems on which it relies, while still aiming to foster spaces for participatory learning, open sharing, and change. Ultimately, it will call for a sector-wide ethics approach to datafication, and invite input on what that could look like.

</p>
</details>
```

### Parallel Session 10.2 {-}

<mark>**Life Sciences Building LSB 105**</mark>

**<mark>[Session Link](https://uvic.zoom.us/j/82916752574?pwd=OG90Z0FwcjNkbmpvY2ZKYzRCVVQ5Zz09)</mark>**

```{block, type='speaker'}

#### GO-GN (Global OER Graduate Network) Panel 

*Researching at the Edge of Openness: Reflections from GO-GN Members*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
GO-GN, the Global OER Graduate Network, brings together a core group of current doctoral researchers working on open education topics, along with the GO-GN team at the Open University, alumni, other researchers and fellow travellers through open space. And though we travel without uniforms or transporters, like members of Starfleet GO-GNers do go boldly, attempting to push the boundaries of knowledge in the field. Recognising the multiple senses in which education can be open, we approach the concept of openness from various angles and use a range of methods.

In this panel discussion members of the network will reflect upon the what, why and how of their doctoral journeys, and invite session participants into our conversation.

</p>
</details>
```

## Concurrent Session 11 |  2:30-3:00 {-}

30 Minutes

### Concurrent Session 11.1 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 103**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}


#### 2:30-3:00 | **An e-Book of One’s Own** |  Practice {-}

***Terry Greene*** | *Trent University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The proliferation of digital technologies has brought about a wealth of opportunities for teaching, learning, and research in higher education. However, many institutions have not fully embraced these technologies to empower their faculty and students to create, collaborate, and share their work online. A combination of Domain of One’s Own and Pressbooks may offer a solution to this problem by providing faculty and students with the tools and structure that they need to create and publish online in a way that is both secure, scalable and not out of reach for all but the most digitally fluent.
In this presentation, we will explore the benefits of combining the practice of Domain of One’s Own with the use of an institutional Pressbooks instance. These benefits include:
- Providing faculty and students with a platform for creating and sharing their work online in a way that focuses on ease of use.  
- Empowering faculty and students to take control of their learning by creating a personal e-book that reflects the growth of their learning throughout their program.  
- Allowing faculty to create and publish open educational resources (OERs) and other digital resources that can be used by students and other educators around the world.  
- Supporting the creation of online communities of practice and collaboration, where faculty and students can share their work, exchange ideas, and provide feedback.   
The presentation will be targeted towards faculty, instructional designers, librarians, and educational technologists who are interested in exploring this approach to teaching, learning, and research. Attendees will learn about the benefits of simplifying Domain of One’s Own with Pressbooks.

</p>
</details>
```

### Concurrent Session 11.2 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 2:30-3:00 | **Impact of Emergency Remote Teaching and Digital Technology Usage in K-12 Teacher Practice** |  Research {-}

***Amber Hartwell*** | *University of Calgary*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Digital technologies are potentially being used more in K-12 classrooms than prior to the COVID-19 pandemic. In efforts to slow the spread of the virus, many schools abruptly transitioned to emergency remote teaching (ERT). Not all teachers and students were familiar with using such tools, but were required to adapt. COVID-19 has resulted in a large amount of research in education; however, studies focused on ERT and its impact on teacher practice is limited. This inquiry explores how ERT has impacted digital technology usage in current K-12 teacher practice. Data has been collected from K-12 teachers enrolled in graduate programs at one large university through an online questionnaire, semi structured interviews, a review of documents provided by interview participants, and analytic memos. Analysis and interpretation of findings is in progress, and will be organized by way of examining the key research questions through Cultural Historical Activity Theory. This research will also reveal digital technologies introduced during ERT, and factors influencing a teacher’s decision to integrate new technologies into current practice. The author will conclude by offering recommendations that may be useful in the work of technological change in K-12 education.

</p>
</details>
```

### Concurrent Session 11.3 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}

#### 2:30-3:00 | **Data Risks in Online Classroom Platforms: A Comparative Analysis of Policy Documents** |  Research {-}

***Thi Kim, Thu Le & Bonnie Stewart*** | *University of Windsor*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Online video conferencing platforms have been widely used as key classroom tools all over the world. In the wake of the Emergency Remote Teaching (ERT) response to COVID-19, however the issues of data risk and privacy that these tools raise in classroom contexts have been minimally addressed for researchers, educators, and students. Additionally, while the ERT online pivot experience was generally global, digital classroom tools and their provenance vary. Many educational technology platforms are developed in the U.S yet used in other countries and jurisdictions. Yet multiple alternate educational technology markets exist in the contemporary world. This paper was designed to explore whether global claims about the potential privacy risks of classroom tools could be made and aims to analyze the policy documents of two popular tools in separate markets: Zoom, developed in the U.S., and ClassIn, developed in China. The paper provides a brief comparison of the relative data risks of these two prominent online classroom platforms. Similarities and distinctions between the two in terms of data transparency, safety, security, protection, rights, and contexts are outlined, but overall, for educators’ purposes, the findings suggest that data privacy implications of Zoom and ClassIn are more similar than they are different.

</p>
</details>
```

<!--
### Concurrent Session 11.4 |  Transitions of Online Learning & Teaching {-}

```{block, type='session'}

#### 2:30-3:00 | 
</p>
</details>
```
-->

## Break with Coffee and Snack Provided | 3:00-3:30 {-}

## Concurrent Session 12 |  3:30-5:00 {-}

1.5 Hours

### Concurrent Session 12.1 |  Transitions of Online Learning & Teaching {-}

<mark>**Life Sciences Building LSB 105**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa)**</mark>

```{block, type='session'}

#### 3:30-4:30 | **L’apprentissage intégré au travail numérique – l’impact de l’éducation sur la pénurie de main-d’œuvre (in French)** |  Practice {-}

***Andrea Krasznai*** | *eCampusOntario*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
We often talk about the labor shortage, but what are the solutions? eCampusOntario offers a Work-Integrated Learning (WIL) project, and in particular digital WIL, as one of the solutions to address this skills gap in the labor market.

eCampusOntario’s WIL project, Consortium d’apprentissage expérientiel francophone de l’Ontario (CAPFO), brings together Francophone and bilingual post-secondary institutions in Ontario to provide experiential learning opportunities for Francophone students. This fills another gap experienced by the Francophone community in Ontario, namely the lack of experiential learning opportunities in Francophone and bilingual environments. Once the match is made on the platform, stakeholders have access to built-in project management and communication tools, which facilitate collaboration. Although this project is specifically aimed at these institutions, the possibilities are endless and borderless allowing students to have an enriching and diverse experience, and on the other hand, employers around the world have access to the next generation of talent.

Teachers and employers now have an equal chance to become major players in bridging the gap between theory and practice, education and work.

</p>
</details>
```

```{block, type='session'}

#### 4:30-5:00 | **Open at the Crossroads: Forging Media and Digital Literacy Pathways** |  Research {-}

***Helen DeWaard*** | *Lakehead University & University of British Columbia*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
In order to re-envision open and online education, and respond to the conference theme of Reckonings and Reimaginings, this session will focus on reckonings with digital technologies and media production in Canadian faculties of education to support a vision of open learning ecospheres while reimagining Marshall McLuhan’s prophetic words “the medium is the message” (McLuhan, 1977). In current times, educators in open and online educational spaces stand at a crossroads, facing media and digital directions and pathways toward uncertain futures. This presentation will begin by exploring past assemblages of media and digital literacies definitions and practices that impact decisions to navigate into the open. Then possible futures for online education are shared. The presenter provides perspectives and directions toward possibilities emerging from their research. The session will conclude with a collaborative and participatory mapping and wayfinding activity to investigate potential pathways toward forging new media and digital trails while exploring uncharted open ecologies together.




 

</p>
</details>
```

### Concurrent Session 12.2 |  Wildcard {-}

<mark>**Life Sciences Building LSB 107**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_2)**</mark>

```{block, type='session'}

#### 3:30-4:00 | **Virtual Reality Simulations in Higher Education Science Classes:Student Engagement and Teacher Professional Development** |  Research {-}

***Sebastien Wall-Lacelle, Bruno Poellhuber*** | *Université de Montréal*

***Christine Marquis*** | *Cégep de Saint-Jérôme*

***Normand Roy*** | *Université de Montréal*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
As the literature reports decreasing levels of student interest, motivation and engagement in science classes, the need to study innovative teaching tools is greater than ever. Virtual reality offer the potential to see and interact with concepts that are invisible or unreachable in a way that students are actively engaged in their learning and have been shown to positively contribute to motivation, engagement and learning. However, these effects are highly dependant on the pedagogical scenario. In this talk, we will present results from a large scale design-based research that brought together 38 teachers and 5 579 students. Using multilevel regression models, we observed that the level of complexity of the pedagogical scenario is a significant level 2 predictor of behavioral engagement. Pedagogical practices associated with high quality pedagogical scenarios will be contrasted with practices associated with low quality pedagogical scenarios and the results of qualitative interviews with students. Moreover, we will present a multicase study on professional development that shows that teachers participating in the project reported significant changes in their pedagogical practice occurring over time converged towards pedagogical scenarisation and active learning.

</p>
</details>
```

```{block, type='session'}

#### 4:30-5:00 | **A Gamified Design Framework to Enhance L2 Learners’ Motivation and Engagement** |  Research {-}

***Mourad Majdoub*** | *Université Laval*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Gamification has been the subject of extensive research as it potentially allows second/foreign language learners to enhance their language learning and, at the same time, foster their motivation and engagement (Koivisto & Hamari, 2019). The reason is that several game elements, embedded in the gamified environments, can increase learners’ interest, can reduce learners’ anxiety and fear of speaking foreign language in front of others, and finally can encourage them to attain a favorable type of learning behavior (Dehghanzadeh et al., 2021). Since gamification is a relatively new concept, and most of the suggested gamified design frameworks are not based on solid theoretical foundations, it is not yet possible to fully understand its effect on the L2 learning process. Thus, the present communication aims at identifying a gamified design framework that would enhance learners’ motivation and engagement in their L2 classes. We have conducted a L2 gamified experiment with high school students where they have been observed interacting with their teacher and pairs. The field notes and a follow-up focus group interview will be qualitatively analysed to suggest a design framework for gamified L2 learning. Preliminary findings will be available in spring 2023, and will be shared at OTESSA conference.

</p>
</details>
```

### Concurrent Session 12.3 |  Sustaining Positive Change {-}

<mark>**Life Sciences Building LSB 101**</mark>

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_3)**</mark>

```{block, type='session'}

#### 3:30-4:30 | **Re/storying Pedagogy for the Postdigital University: Examining the Power of Critical Storytelling for Imagining Better Futures** |  Practice {-}

***Danielle Dilkes*** | *Western University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Education in the postdigital world challenges existing ideas of instructor and learner identities and practices. In spite of institutional demands that we “get back to normal”, there is no going back. There is only going forward. We are at a pivotal point in defining what the future of education could be. Is this future bleak and dystopian? Or is it one of hope and radical change?
This session invites instructors, academic staff, students, or others involved in the relational practice of teaching and learning to reflect on, challenge, and rewrite the stories that shape emerging practices in education. We will examine how identity and pedagogy are complex and sociomaterial, similar to a game of Cat’s Cradle, consisting of multiple strands, knots, and tensions (Haraway, 1994). Using entangled storytelling, we will explore this web of knotted influences, revealing hidden values, motivations and assumptions in education. We will then engage in speculative storytelling by reflecting on what could happen if we cut one thread or undo one knot, or if a new knot is tied or more strands are introduced. By engaging in both entangled and speculative storytelling, this session will open up new ways of thinking about and practicing education.

</p>
</details>
```



### Concurrent Session 12.4 |  Sustaining Positive Change {-}

<mark>**[Experimental web radio link to the audio of this session.](https://radio.uvic.ca/public/otessa_4)**</mark>

<mark>**Life Sciences Building LSB 103**</mark>

```{block, type='session'}

#### 3:30-4:00 | **Reviewing the Strengths and Challenges to Peer Review** |  Research {-}

***Connie Blomgren*** | *Athabasca University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Along with many other aspects of research and the academy, there is some discussion of the role, function, strengths and challenges of peer review. Although double-blind peer review is the most accepted process for submissions to research journals changes are afoot. In addition to open reviews other changes are being experimented with various journals. With the advances to artificial intelligence and implications for all forms of writing, including scholarly documents, there is a timeliness to reassessing the strengths and challenges to peer review. Viewed within Hegarty’s Open Pedagogy framework and open access articles as one type of open educational resource, peer review takes on a more complex role within the move toward educational change.

</p>
</details>
```

```{block, type='session'}

#### 4:00-4:30 | **A Review of Research on Open education Adoption in higher Education: Exploring Approaches, Readiness, and Methods for Evaluation** |  Research {-}

<mark>**Life Sciences Building LSB 103**</mark>

***Michael Paskevicius & Valerie Irvine*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The University of Victoria has recently received internal funding to develop the UVic Open Hub. This will be a portal for fostering a community to support open education dialogue, collaboration, and initiatives across the campus, including open teaching and learning resources, sharing approaches to open teaching, and open scholarship. As UVic is not the first to engage in such a project, we will share the results of a literature review that explores a) institutional approaches to expanding adoption of open education, b) faculty readiness to engage with open, and c) evaluation methods used to measure impact. As well, we hope to engage the audience in learning how they have experienced institutional initiatives towards open education and collaboratively develop a set of strategies and approaches for sharing.

The goal of the UVic Open Hub is to shift culture to increase the availability, access, reuse, and redistribution of knowledge artifacts and to support the participation of stakeholders, including undergraduate and graduate students, staff, faculty, and administrators, in areas spanning research (open access, open scholarship, open data), teaching and learning (open education, open pedagogy, open educational resources), and service (connecting open practices for community engagement, marketing, and recruitment). Taking an expansive approach that goes beyond the creation and adoption of open educational resources we hope to develop a culture of open scholarship using a bottom-up approach by engaging with individual academic units.

</p>
</details>
```

```{block, type='session'}


#### 4:30-5:00 | **Research? Which Research? Technology, Assessment, and Higher Education in Tension** |  Research {-}

<mark>**Life Sciences Building LSB 103**</mark>

***Colin Madland*** | *University of Victoria*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Utilizing Bower’s technology-mediated learning theory as a framework, participants will be invited to engage in generative conversation about possible approaches to resolving the problem of fragmented and siloed bodies of literature related to technology-integrated assessment in higher education. Technology-integrated assessment practices in higher education are under scrutiny with another ‘existential threat’ in the form of automated text-generation. For those whose disciplines require extensive writing or coding, this has led to a certain lament regarding what appears to be at risk: the ability to trust that learners have engaged in the cognitive work of sense-making and are presenting the results of that work. In my own observations and in the process of reviewing the literature on technology-integrated assessment in higher education, responses to this development seem to map to distinct bodies of literature with weak connections between them. Responses seem to be oriented towards technology, assessment approaches, or individual disciplinary perspectives. The links between these siloed bodies of literature and on-the-ground difficulties in reacting to challenges to technology-integrated assessment in higher education will be problematized and explored and participants will engage in conversation to spark and sustain positive change for the good of the academy and society.

</p>
</details>
```

## See Congress Programming for Social Tent & Food Options | 5:00-7:00 {-}

## OTESSA Social |  Life Sciences Building Lobby | 7:00-11:59 {-}
