# Friday, June 2 - Online Sessions Only

```{block, type='protip'}

#### There is no #OTESSA23 Morning Radio Show today.
```

### Session Types {-}

```{block, type='protip'}


#### ✨ Note{-}

***All times are in Eastern Time (Canada)***
```

```{block, type='keynote'}

#### Keynote

```

```{block, type='speaker'}

#### Invited Speaker

```

```{block, type='session'}

#### Regular Session

```

```{block, type='social'}

#### Social Session

```

```{block, type='vendor'}


#### Vendor

```

```{block, type='workshop'}


#### Workshop

```

---

## Welcome Desk Open | 10:00 - 12:30 {-}

## Conference Welcome, Announcements & Land Acknowledgement | 10:30-11:00 {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/87072450625?pwd=d3dSNG9SQ0lkZXByUElDK3EycG82QT09){target="_blank"}</mark>

## Keynote | 11:00-12:00    {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/83832291664?pwd=M0pvTFNCWDBsRWd1NFJKaC9BbjM1QT09){target="_blank"}</mark>

```{block, type='keynote'}
 

#### The (un)bearable lightness of student data privacy: reckonings and re-imaginings {-}

[***Paul Prinsloo*** | *University of South Africa*](https://otessa.github.io/2023/keynotes.html#paul-prinsloo)

<details>
<summary><b>Abstract</b></summary>
<p>
Education has always collected and used student learning data in combination with a range of other data e.g., demographic, financial and prior learning data for a variety of purposes such as to assess and monitor students’ progress, identify students who may need additional support. There has always been concerns about possible bias, stereotyping and impact of categorization of students. Students’ (data)(learning) privacy were somewhere to be found among files being carried from one office to the other, files that got misplaced, unlocked storages and, possibly, a laissez-faire approach to protecting student data privacy because what happened in the classroom and school, stayed in the classroom (mostly). Even if this portrayal of student data privacy may sound idealistic and rather, simplistic, we must reckon how the increasing digitalization and datafication of teaching and learning changes not only the scope of student (data) privacy, but also attempts to protect their (and our) data. In this presentation I hope to provoke thinking about the (un)bearable lightness of student data privacy and consider what it means for students, faculty, institutional data governance amid the intensification and expansion of the data gaze. 

</p>
</details>


##### [Session Link](){target="_blank"} {-}

```

## Break | 12:00-12:30 {-}

## Unconference on Digital, Online, and Open Education (Online via Zoom) | 12:30-1:15 {-}

(45 minutes)

<mark>[**Session Link**](https://uvic.zoom.us/j/86010785627?pwd=Nm83LzM1RXRXQU9JVFJldWg3RmhPZz09){target="_blank"}</mark>

An unconference is a participant-driven session meant to reduce emphasis on formal speeches and to avoid the hierarchical aspects of a didactic conference session. All Congress attendees are welcome to participate in this face-to-face unconference; however, participants registered with the OTESSA conference will be sent an invitation for topic suggestion and upvoting to select the break-out room topics in advance. At the time of this session, the topic-to-room assignments will be complete and posted on our program website at <https://otessa.org/2023/program/>. You are welcome to move between topic rooms and come and go as you please! We look forward to welcoming targeted discussion on your favourite topics! Please note that this is the in-person unconference. There will also be an in-person unconference that will take place on Tuesday, May 30 from 11:00 am - 12:00 pm in the Life Sciences Building at York University as part of the OTESSA Conference.

## Break | 1:15-1:30 {-}

## Concurrent Session 18 | 1:30-3:00 {-}

1.5 Hours

### Concurrent Session 18.1 |  Transitions of Online Learning & Teaching {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/82898272461?pwd=OW50MHEyajd1SUNLTDRWTHNkdzJUQT09){target="_blank"}</mark>

```{block, type='workshop'}


#### 1:30-2:30 | **Assessment in a Digital Age: Learning within the Continuum for Pedagogy, Technology, and Assessment** |  Workshop {-}

***Barbara Brown & Nadia Delanoy*** | *University of Calgary*

***Jodie Walz*** | *Calgary Catholic School District*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
As a result of an observation that preservice teachers and in-service teachers need more hands-on opportunities to engage in digital assessment practices to prepare for more technology-enhanced learning environments, a research and practice collaboration emerged between a faculty of education and school district educational technologists. This design-based study involved designing an online professional learning series aimed to develop teachers’ formative and summative assessment practices using technology enhanced practices. Through engaging participants in reflection and time to engage with technology-enhanced methods, we used a theory to practice design as well as the TPACK framework to explore the relationship between: (1) technology, (2) teaching pedagogy, and (3) content knowledge. The results from this study demonstrated the importance of designing assessment through an interconnected lens prioritizing the centricity of technological, pedagogical, and content knowledge. Additionally, the research indicated participant efficacy when engaging in pedagogical applications of assessment with technological constructs suited to their teaching and learning environments. The complexities afoot within the duration of this work spanned not only the beginning of the pandemic but now the realities embedded in an emerging post-pandemic context.

</p>
</details>
```

```{block, type='session'}

#### 2:30-3:00 | **Reflections on an Emerging National Strategy for Open Education** |  Report {-}

***Bradley Wuetherick*** | *University of British Columbia – Okanagan Campus*

***Valerie Irvine*** | *University of Victoria*

***Ann Ludbrook*** | *Toronto Metropolitan University*
<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Over the past decade, higher education institutions, organizations, and governments have advocated for, and invested in, open education – particularly focusing on the ways open education can mitigate ongoing accessibility and affordability concerns. And while there have been a number of initiatives to coordinate these activities, there has not been a national strategy for open education in Canada. Over the past two years, Open Education advocates (faculty, librarians, administrators, and representatives of organizations across the country) have begun meeting to work towards the development of a national Open Education strategy. To further this work, they have worked together to host one National Summit with two additional Summits to follow, focusing on francophone OER, and the intersection of Indigenous Knowledges and OERs. This session will focus on the reflections of four individuals involved in these national conversations, focusing on the impetus behind the development of a national Open Education strategy, the importance of the three Summits (already hosted or planned), and why the development of a national strategy is a priority for Canadian higher education.
</p>
</details>
```

### Concurrent Session 18.2 |  Transitions of Online Learning & Teaching {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/84849983422?pwd=V0NDeVhSUjA2eDF5M2U2QUU0OFUvZz09){target="_blank"}</mark>

```{block, type='session'}

#### 1:30-2:00 | **Open Education Research: Past, Present, Future** |  Research {-}

***Robert Farrow, Beck Pitt, Martin Weller, Paco Iniesto & Carina Bossu*** | *The Open University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The Global OER Graduate Network (GO-GN, n.d.) supports doctoral research in open education around the world and currently has several hundred members who are doctoral/post-doctoral researchers and interested expert practitioners. In this presentation we offer some analysis of trends in research into open education, drawing on the data generated by GO-GN as well as other expert research.
We provide an analysis of network activity and identify core areas for contemporary open education research, including open practice, OER as a discipline area, making connections between research clusters and the application of OER in non-traditional learning contexts. We also offer some reflections on the evolving nature of discourse around open education and the relation between research and practice, particularly around the themes of social justice and equity, diversity and inclusion.

</p>
</details>
```

```{block, type='session'}


#### 2:00-2:30 | **Using Qualitative Online Survey as a Research Method Amid Covid Pandemic** |  Practice {-}

***Yina Liu*** | *University of Alberta*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Online survey becomes one of the popular/favorite methods for conducting research under the Covid-19 pandemic. The method allows researchers to collect data without in-person interaction, also provides convenient processes for both researchers and participants to engage a survey in terms of delivering surveys and giving responses. However, the actual situations in data collection may not be described as convenient. This paper will present an autoethnography study of a researcher’s own experiences of conducting qualitative online survey during Covid-19 in Canada. The researcher used online qualitative survey to explore newcomer children’s digital literacy practices and their parents’ perspectives towards digital practices. This presentation will provide suggestions for future survey researchers, in terms of effective strategies of collecting data.

</p>
</details>
```

```{block, type='session'}


#### 2:30-3:00 | **Technological Distance: A New Way of Conceptualizing the “Distance” in Distance Learning** |  Research {-}

***Jon Dron*** | *Athabasca University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
This paper presents the concept of technological distance, which describes a gap between technologies (broadly defined to include methods, tools, principles, and processes) available for a learner to learn, and those needed to complete that learning. This gap is a measure of both the participation and autonomy of learners in the process. Available technologies may include those provided by teachers and institutions as well as from many others, most notably including the learners themselves. The technologies that make up the assembly are only components, however. What matters most is how learners fill the gaps between them to achieve their learning goals. These are fundamentally situated, idiosyncratic, and human. Technological distance provides new insights into other models that use spatial metaphors, such as the presences of communities of inquiry and transactional distance.

</p>
</details>
```

### Concurrent Session 18.3 |  Wildcard {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/81832796337?pwd=d2lkclVtby9lZUo3QkZMR2V5RzFKdz09){target="_blank"}</mark>

```{block, type='session'}


#### 1:30-2:00 | **Non-Directive Strength-Based Online Coaching in Graduate Education** |  Research {-}

***Carolyn Kristjansson*** | *Trinity Western University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Online and blended modes of graduate education have become increasingly prevalent in recent years, often resulting in online learning spaces comprised of adult learners with a wide range of life experiences from diverse cultural contexts and language backgrounds. A key consideration is how best to support such learners to facilitate a sense of belonging and engagement (Jeng, Bosch, & Perry, 2023), conditions some researchers consider fundamental to academic success (Roddy, et al., 2017). One possibility is through coaching. This presentation reports on the initial results from a case study investigating students’ experience of non-directive strength-based online coaching support in a Master’s in Teaching English to Speakers of other Languages (MA TESOL) program.

The case study is guided by theoretical understandings of the learning environment as a complex dynamic system (Dornyei, 2014) and coaching as a social practice (Author) that can be characterized by positive or negative emotional attractor states (Boyatzis, Rochford, & Taylor, 2015). The presentation provides an overview of preliminary quantitative and qualitative analysis to illuminate the value of the online coaching experience from the perspective of graduate students who were coached.

</p>
</details>
```

```{block, type='session'}


#### 2:00-2:30 | **The Teacher’s Self-efficacy and Belief in Implementing S STEM, iSTEM or STEAM in their Classroom** |  Research {-}

***Atiya Razi*** | *University of Windsor*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
In recent years, STEM, iSTEM (Integrated STEM), and STEAM (STEM paradigms) have revolutionized the educational paradigm. Researchers, educators, and professionals globally consider STEM paradigms their saviours (Kuenzi, 2008), which have reckoned and reimagined the educational archetype. This study is grounded in Bandura’s self-efficacy theory and socio-cultural constructivist learning theories. Successful STEM, iSTEM, and STEAM delivery are linked to the teachers’ self-efficacy and beliefs in their classroom because it motivates students, develop a positive attitude toward STEM subjects, and enhance students’ 21st-century competency (Kanadlı, S., 2019). This study aims to fill a research gap by examining teachers’ perspectives on STEM paradigms and their integration together by exploring current and past pedagogies. Researchers and educators will also benefit from this study by exploring teachers’ challenges when implementing STEM paradigms in their classrooms. Finally, the study examines the factors that support teachers in implementing STEM paradigms in the classroom. A mixed-methods approach will be employed, involving surveys and interviews. The results from this study will offer a solid knowledge basis for interested students, educators, researchers, and policymakers with the strategies needed for the successful execution of STEM in school; professional development; generating and designing the education policy that supports STEM education, STEM career development, and the job market, especially in Canada.

</p>
</details>
```

```{block, type='vendor'}

#### 2:30-3:00 | **Leveraging Social Annotation in the Age of AI** |  Research {-}


***Jessica Fuller*** | *hypothes.is*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The emergence of cutting-edge technologies, like ChatGPT, has sparked a critical conversation throughout the world of education. In this session, Jessica from Hypothesis will show how to leverage social annotation to encourage authentic, process-oriented engagement with course materials. She’ll also share best practices for using social annotation with AI writing tools and demonstrate how to set up Hypothesis-enabled readings in your LMS. Participants can expect to leave the session armed with concrete assignment ideas to implement in courses right away.
</p>
</details>
```

### Concurrent Session 18.4 |  Addressing Inequities {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/87836094846?pwd=UnRMVERJQUtLZW13NEFkZ2hmM0hLZz09){target="_blank"}</mark>

```{block, type='session'}

#### 1:30-2:30 | **Four Perspectives of Learner-Educator Co-Creation** |  Practice {-}

***Mercedes Lock*** | *Cambrian College*

***Jane Tyerman*** | *University of Ottawa*

***Lillian Chumbley*** | *Trent University*

***Laura Killam*** | *Queen's University Canada*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
In this panel discussion we will discuss the challenges and benefits of learner-educator co-creation from a variety of interdisciplinary perspectives. Our focus will be on answering the audience’s questions about learner-educator co-creation. We will also bring some common questions that we have received from others to begin the conversation should the audience need time to ponder their questions.
Panelists will represent different aspects of co-creation across both academia and professional development uses. Panelists have experience implementing and supporting co-creation as learners, students, educators, partners and support staff in undergraduate and graduate courses, professional development, and industry contexts.

The panel discussion will be supported by a virtual backchannel that will foster participant engagement in the discussion, allow for crowdsourcing of notes and materials, and asking of questions. Our hope is to create a meaningful discussion to support those who are new to co-creation or looking for ways to improve their co-creation practice.

</p>
</details>
```

```{block, type='session'}

#### 2:30 - 3:00  | **A Learner-Educator Co-Creation Toolkit** |  Practice {-}

***Laura Killam*** | *Queen’s University Canada*

***Lillian Chumbley*** | *Trent University *

***Jane Tyerman*** | *University of Ottawa*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Co-creation occurs when learners and educators work together to make decisions during a course. Shared decision-making may occur in relation to one or more components of a course such as content curation or designing assessments. This partnership has many potential benefits including student empowerment, promotion of improved relationships, and metacognition, but educators may be hesitant to try it because they are concerned about pragmatic limitations. These limitations may include the time involved, technical requirements, and engaging large classes. In addition, questions about academic integrity concerns may arise.

In this presentation we share and seek collaboration on a drafted toolkit for learner-educator co-creation. Our goal is to provide a location where educators can easily access tools that will help them effectively engage in co-creation related to a spectrum of small to larger learning decisions. In this presentation we will discuss opportunities to improve this toolkit and engage in an ongoing community of practice.

</p>
</details>
```

### Concurrent Session 18.5 |   Sustaining Positive Change{-}

<mark>LINK TBC</mark>

```{block, type='session'}

#### 1:30 - 2:30  | **Scaling Small: The Open Book Collective Launch and Platform** |  Practice {-}

***Judith Fathallah*** | *Lancaster University*


<!--
**Keywords:** 
-->

<details>
<summary>**Abstract**</summary>
<p>
The Open Book Collective, scheduled to launch November 2022, brings together Open Access book publishers, scholarly librarians, and OA infrastructure providers, working towards a sustainable and equitable future for OA books. This session will introduce our work, then demonstrate the use of the Open Book Collective membership platform, which will be live by the time of the conference. The Open Book Collective operates according to the principle of Scaling Small, which has guided the work of its umbrella project, Community-Led Open Infrastructures for Open Access Books (COPIM). ‘Scaling Small’, as opposed to ‘scaling up’, is an alternative way of envisaging a publishing and distribution ecosystem for Open Access Books that is based on mutual reliance and other kinds of collaboration rather than competition and incorporation. We believe that economies of scale flatten community diversity and lead to unhealthy monopolies. More pragmatically, the OBC requires a commitment from our publisher members to move away from book processing charges, which are both unsustainable and deeply inequitable. The introduction and interactive demonstration will be followed by a Q and A.

</p>
</details>
```
## Break | 3:00-3:15 {-}

## Social | 3:15-3:45 {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/87072450625?pwd=d3dSNG9SQ0lkZXByUElDK3EycG82QT09){target="_blank"}</mark>

```{block, type='social'}

#### Music with Jon Dron {-}

```

## Concurrent Session 19 | 3:45-5:15 {-}

1.5 Hours

### Concurrent Session 19.1 |  Wildcard {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/82898272461?pwd=OW50MHEyajd1SUNLTDRWTHNkdzJUQT09){target="_blank"}</mark>

```{block, type='session'}


#### 3:45-4:45 | **On Speculative Education Fiction for Hopeful Learning Futures** |  Research {-}

***Shandell Houlden & George Veletsianos*** | *Royal Roads University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
In this session, we discuss reimagining education futures by examining the limits and potentialities of speculative research methods, with focus on the distinction in the literature between pessimistic visions of the future, which are visions exploring themes such as disconnection, lack of autonomy and sovereignty, and technological, corporate, state and/ or authoritarian control, and hopeful futures. Hopeful speculative education futures are shaped by themes such as connection, agency and community and individual flourishment, and suggest a turn to the genres of hopepunk, solarpunk and visionary fiction as models of speculative storytelling grounded in hope. A focus on these more liberatory futures serves to disrupt the over-reliance on pessimistic storytelling, which itself is related to apocalyptic storytelling, which risks reinforcing inequality, especially with respect to settler colonial injustice.

</p>
</details>
```

```{block, type='session'}

#### 4:45-5:15 | **Wait… What? Examining SSHRC Funding Structures and Processes With a Focus on its Implications on Equitable Access for Educational Researchers** |  Research {-}

***Valerie Irvine*** | *University of Victoria*

***Sonja Johnston*** | *University of Calgary*

**Keywords:**

<details>
<summary><b>Abstract</b></summary>
<p>
Access to federal government funding to support research in the social sciences has always been a highly competitive process for faculty and graduate students. As scholarship is becoming increasingly interdisciplinary, we are observing challenges in terms of ensuring pathways to support a review process specifically for interdisciplinary research, while also ensuring equitable access to tri-agency funding across the three council (Social Sciences and Humanities Research Council (SSHRC), Natural Sciences and Engineering Research Council (NSERC), and Canadian Institutes of Health Research (CIHR)) as well as between disciplines on committees within SSHRC. As educational researchers, we have noted trends that put educational researchers, housed in Faculties of Education, at a possible disadvantage. We will also touch on the additional burden that marginalizes researchers and graduate students in educational technology, who face a “second shift” in terms of continually developing and updating digital literacies and online learning pedagogies. In this session, we will review publicly available data and share personal observations of the process, which includes direct experience as a repeated reviewer of SSHRC doctoral applications in Ottawa. We will share steps being taken to open dialogue and to make recommendations for next steps as we hope to collect data to inform recommendations for change. We welcome participants to provide input on strategies for creating change for fair access to funding for education.

</p>
</details>
```

### Concurrent Session 19.2 |  Sustaining Positive Change {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/84849983422?pwd=V0NDeVhSUjA2eDF5M2U2QUU0OFUvZz09){target="_blank"}</mark>

```{block, type='session'}


#### 3:45-4:45 | **“No Longer Silent!” Racialized Academic Women Speak Out** |  Research {-}

***Sandra Dixon*** | *University of Lethbridge*

***Cecille DePass*** | *University of Calgary*

***Dawn Edge*** | *The University of Manchester*

***Mille Batta*** | *University of Lethbridge*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Given that racialized academic women are impacted negatively in academia (Canadian Association of University Teachers [CAUT], 2018; National Center for Education Statistics [NCES], 2020), this research contributes directly to promoting positive changes in the academy and larger society. The research question explores: How can the scholarship and research for Equity, Diversity, and Inclusion (EDI) among racialized academic women enhance and strengthen multiple disciplines, policymaking and administration in academia? This inquiry aligns with OTESSA’s Mission to advance innovative research and disseminate data outcomes as part of knowledge mobilization. This session supports the conference’s theme since it aims to promote EDI in education, scholarship, and society. Grounded in research, this presentation lays the foundations for increased policy-making and institutional consciousness, inclusive community building, and cultural sensitivity within academia. The Intersectionality Theory that informs this work reveals a complex picture of the ways that racialized groups are othered in society (Crenshaw, 1989). Document analysis (Morgan, 2022), the methodological approach that underpins this research explores a first-person account of an individual’s actions, experiences, beliefs, and worldviews (Bowen, 2009). This session concludes with a call for action that offers concrete strategies to inform policy and practice provincially, nationally, and internationally. Attendees will be invited to explore thought-provoking questions and consider how they navigate racialized academic contexts.

</p>
</details>
```

```{block, type='session'}


#### 4:45-5:15 | **Peace Education in the Platformed Society: Lessons from Colombia** |  Research {-}

***Estaban Morales*** | *University of British Columbia*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
In Colombia, peace education has been recognized as essential to changing prevailing violence narratives. And, as peace education seeks to respond to the lives and needs of citizens, it has become increasingly necessary to consider how peace and violence are transformed by digital platforms such as social media. Indeed, platforms such as Facebook, Twitter, and WhatsApp have transformed how Colombians experience and interact with ecologies of violence that affect them and their communities. Accordingly, this paper will explore how reflection, dialogue, and imagination on violence on social media are venues of transformative learning. In this study, 18 Colombian young adults explored, discussed, and reflected on social media violence as they experienced it in their everyday lives. Results of this study show that critical conversations among peers can support young adults’ learning processes around both media literacies and peace education, where they can better identify, understand, and address harmful behaviour online and offline. Overall, this presentation highlights the need to incorporate digital environments into efforts to build and sustain cultures of peace.

</p>
</details>
```

### Concurrent Session 19.3 |  Wildcard {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/81832796337?pwd=d2lkclVtby9lZUo3QkZMR2V5RzFKdz09){target="_blank"}</mark>

```{block, type='workshop'}


#### 3:45-5:15 | **Designing Pedagogy for Immersive Experiences** |  Workshop {-}

***Joannie Girard*** | *Conseil scolaire Viamonde*

***S Girouard*** | *Conseil Scolaire Catholique Mon Avenir*

***Lorayne Robertson*** | *Ontario Tech University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Virtual reality is a technology where users are immersed in a digital world created by a computer and accessed through a headset (Dalton, 2021). Virtual reality has been shown to enhance learning in healthcare and safety training because it simulates the real environment vividly. Early explorations of VR use in education show that it provides a cost-effective and visually-stimulating field trip experience that engages students in new ways. There are, however, other advantages to the use of VR and these are connected with the level of immersion that it affords the user. In an immersive VR setting, participants have autonomy to explore the virtual environment, interact with objects and other people, and create spaces suited to different learning needs. In the proposed workshop, participants will be able to access VR through their phones, computers or using a headset. The workshop employs Spatial, a software platform that facilitates real time collaboration in the virtual environment. This technology was recently used successfully for professional development for teachers in Ontario in geographically-remote French-language school districts. In this workshop, participants will gain a sense of co-presence in VR and see the potential for employing these polysynchronous learning spaces in education.
</p>
</details>
```

### Concurrent Session 19.4 |  Sustaining Positive Change {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/87836094846?pwd=UnRMVERJQUtLZW13NEFkZ2hmM0hLZz09){target="_blank"}</mark>

```{block, type='session'}


#### 3:45-4:15 | **Discovery Based Learning with Open Technologies, for Positive Change** |  Practice {-}

***Brian Sutherland*** | *University of Toronto*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
The fields of design and ubiquitious or pervasive computing underscore many academic disciplines – few have been unaffected by the design of systems, the advent of high speed communication capabilities and the proliferation of computing devices. Increasingly, these relations are facilitated by open frameworks and communities in hardware, software, and pedagogy. In this session I discuss a fourth year capstone course in digital design where students in groups engaged with open code libraries and small computers to create sensing devices and systems to aid positive change in healthcare, biology and/or the environment. It revives a pedagogy known as discovery-based learning where the outcome is uncertain, the problems – complex, and the knowledge – extensively articulated and emergent. Learners completed guided practicals mentored by other students, instructional staff, and online resources, supported by their search and evaluation skills, to scaffold their rapid development in a complex, in many cases previously unknown subject domain. The result wasn’t so much working prototypes as simulations of capability and a rich conceptual understanding of the underlying socio-technical systems of development, aided by twenty-first century skills such as search and critical evaluation of sources, online networking, group collaboration, and global citizenship for positive change.

</p>
</details>
```

```{block, type='session'}


#### 4:15-4:45 | **Interprofessional Healthcare Simulation Co-Creation: A Pilot Study** |  Research {-}

***Laura Killam*** | *Queen's University Canada*

***Jacqueline Vaughn, Alicia Sellon, Chase DuBois, Amelia Huelskamp, Andrea Smith, Colette Waddill & Justine Reel*** | *University of North Carolina Wilmington*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Background: Co-creation, interprofessional education, and simulation are strategies that may prepare healthcare students to manage real-world challenges in teams. Faculty identified both a desire to engage in collaboration with students and a need to leverage student creativity to aid in closing the gap in available resources on campus.

Aim: In this presentation we share the results of a multi-method pilot study that aimed to test the development of a course wherein students partnered with faculty in a design challenge to co-create evidence-based interprofessional simulations. The focus of this study was to assess project feasibility and student perceptions of how the experience shaped their learning.

Methods: The intervention was a three-day design challenge where students co-created a simulation with faculty in interprofessional groups. We measured interprofessional competencies before and after the intervention, collected open-ended feedback about student learning, and assessed feasibility (time requirements, resources) of students co-designing a simulation.

Results: This strategy was found to be feasible, effective, unique, and valuable. Students expressed a desire for more learning similar to this experience. Conclusion: Learner-educator simulation co-creation may be a viable strategy to improve student interprofessional competencies and enrich learning. More research on a larger scale is needed.

</p>
</details>
```

```{block, type='session'}


#### 4:45-5:15 | **Negotiating an Informed Personal Theory and Philosophy of Open Education in a Professional Development Setting** |  Research {-}

***Irwin DeVries*** | *Royal Roads University*

***Emily Schudel & Kimberlee Carter*** | *Kwantlen Polytechnic University*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
This presentation is offered by three experienced higher education professionals who have an interest in open education. It is focused on their own practice as reflected in a professional development program they are taking, which is the setting for this presentation. This program focuses not only on the resources and techniques of open education, but also on the purposes and goals of open education, including questions of social justice.

In this session the presenters will share reflections on their experience of the first course in the program, which is focused on theory and philosophy of open education. This course led participants through an exploration of histories, meanings and purposes of open education, while integrating literature, discussions and examples from participants’ own practice.

A critically reflexive collaborative approach (Hamilton & Pinnegar, 2014) is used to describe, compare and analyze their experiences. We approach these topics from the perspective that openness is “contextual, but it is also personal and continually negotiated” (Cronin, 2017. P. 8) and therefore we situate our understanding in within our individual practices.

</p>
</details>
```

## Break | 5:15-5:30 {-}

## Concurrent Session 20 | Invited Speakers | 5:30-6:15 {-}

45 Minutes

### Concurrent Session 20.1 {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/89906555580?pwd=bndpdDZUZkNJa3VIY1UxeGVCbDdOQT09){target="_blank"}</mark>

```{block, type='speaker'}

#### Nadia Naffi | Université Laval 

*Embracing the Metaverse: FormationMeta and the Future of Immersive Learning Experiences (in French)*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Delve into the exciting world of FormationMeta, a groundbreaking 14-week exploratory project spearheaded by Laval University's Chair in Educational Leadership on Innovative Pedagogical Practices in Digital Contexts – National Bank, in partnership with Laval University Library and OVA. This innovative project provided Laval University's learning experience designers and instructors with an authentic experience to cultivate their skills in designing and developing immersive learning experiences within virtual reality and the metaverse. Engaging students from diverse disciplines such as educational technology, art, and game design, the project harnessed the power of StellarX.ai software to create bespoke immersive training tailored to the library's clientele.

Presented in French, this talk will unveil emerging recommendations to enlighten educational teams eager to embrace immersive learning experiences. The speaker will address pressing questions, including the current possibilities and future technological advancements, such as generative AI, essential skills for developing learning experiences in the metaverse, and strategies for training expert groups in education and educational technology to create immersive experiences that effectively cater to learner groups while adhering to ethical, equitable, and inclusive principles.

</p>
</details>
```

### Concurrent Session 20.2 {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/84461790793?pwd=S1JqcC9FejBtREMrOEJjVGxwVFRhUT09){target="_blank"}</mark>

```{block, type='speaker'}

#### Randy LaBonte | Vancouver Island University & Canadian eLearning Network 

*Design Principles for Digital Learning and NSQOL Standards: Commonalities & Differences*

<!--
**Keywords:** 
-->

<details>
<summary><b>Abstract</b></summary>
<p>
Join this session to gain an understanding of design and organization principles to help inform quality in K-12 online learning teacher and leader practices. Learn about the Canadian-based online learning design principles and their commonalities and differences to the US-based National Standards for Quality Online Learning (NSQOL), application to pedagogy and practice, and how the elucidation and clarification of design and organization principles help inform leadership and administrative policy for quality online learning.

</p>
</details>
```

## Conference Closing | 6:15-6:30 {-}

<mark>[**Session Link**](https://uvic.zoom.us/j/87072450625?pwd=d3dSNG9SQ0lkZXByUElDK3EycG82QT09){target="_blank"}</mark>
